const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Pin,
		C3.Plugins.Keyboard,
		C3.Plugins.Button,
		C3.Plugins.Mouse,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Behaviors.solid,
		C3.Plugins.video,
		C3.Behaviors.Tween,
		C3.Behaviors.Timer,
		C3.Behaviors.EightDir,
		C3.Behaviors.jumpthru,
		C3.Behaviors.Sin,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Plugins.Touch,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Behaviors.EightDir.Acts.Stop,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Cnds.CompareAnimSpeed,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.ScrollToObject,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Cnds.OnFrameChanged,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.video.Acts.SetLooping,
		C3.Plugins.video.Acts.SetSource2,
		C3.Plugins.video.Acts.Play,
		C3.Plugins.video.Acts.SetPlaybackRate,
		C3.Plugins.video.Cnds.HasEnded,
		C3.Plugins.video.Acts.Pause,
		C3.Plugins.video.Cnds.IsPaused,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.jumpthru.Acts.SetEnabled,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Platform.Cnds.IsOnFloor
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{Pin: 0},
	{Sprite2: 0},
	{Keyboard: 0},
	{Button: 0},
	{Button2: 0},
	{Sprite8: 0},
	{Sprite7: 0},
	{Sprite9: 0},
	{Mouse: 0},
	{Button3: 0},
	{Browser: 0},
	{Sprite35: 0},
	{Audio: 0},
	{Solid: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Video: 0},
	{Tween: 0},
	{Sprite6: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{Sprite25: 0},
	{Sprite26: 0},
	{Sprite27: 0},
	{Sprite28: 0},
	{Sprite29: 0},
	{Sprite30: 0},
	{Sprite31: 0},
	{Sprite32: 0},
	{Sprite33: 0},
	{Sprite34: 0},
	{Sprite36: 0},
	{Sprite37: 0},
	{Sprite38: 0},
	{Timer: 0},
	{Sprite39: 0},
	{Sprite40: 0},
	{Sprite41: 0},
	{Sprite42: 0},
	{Sprite43: 0},
	{Sprite44: 0},
	{Sprite45: 0},
	{Sprite46: 0},
	{Sprite47: 0},
	{Sprite48: 0},
	{Sprite49: 0},
	{Sprite50: 0},
	{Sprite51: 0},
	{Sprite52: 0},
	{Video2: 0},
	{Sprite53: 0},
	{Sprite54: 0},
	{Sprite55: 0},
	{Sprite56: 0},
	{Sprite57: 0},
	{Sprite58: 0},
	{Sprite59: 0},
	{Sprite60: 0},
	{Sprite61: 0},
	{Sprite62: 0},
	{Sprite63: 0},
	{Sprite64: 0},
	{Sprite65: 0},
	{Sprite66: 0},
	{Sprite67: 0},
	{Sprite68: 0},
	{Sprite69: 0},
	{Sprite70: 0},
	{Sprite71: 0},
	{Sprite72: 0},
	{Sprite73: 0},
	{Sprite74: 0},
	{Sprite75: 0},
	{Sprite76: 0},
	{Sprite77: 0},
	{Sprite78: 0},
	{Sprite79: 0},
	{Sprite80: 0},
	{Sprite81: 0},
	{Sprite82: 0},
	{Sprite83: 0},
	{Sprite84: 0},
	{Sprite85: 0},
	{Sprite86: 0},
	{Sprite87: 0},
	{Sprite88: 0},
	{Sprite89: 0},
	{Sprite90: 0},
	{Sprite91: 0},
	{Sprite92: 0},
	{Sprite93: 0},
	{Sprite94: 0},
	{Sprite95: 0},
	{Sprite96: 0},
	{Sprite97: 0},
	{Sprite98: 0},
	{Sprite99: 0},
	{Video3: 0},
	{Sprite100: 0},
	{Sprite101: 0},
	{Sprite102: 0},
	{Sprite103: 0},
	{Sprite104: 0},
	{"8Direction": 0},
	{Sprite105: 0},
	{Sprite106: 0},
	{Sprite107: 0},
	{Sprite108: 0},
	{Sprite109: 0},
	{Sprite110: 0},
	{Sprite111: 0},
	{Sprite112: 0},
	{Sprite113: 0},
	{Sprite114: 0},
	{Sprite115: 0},
	{Sprite116: 0},
	{Sprite117: 0},
	{Sprite118: 0},
	{Sprite119: 0},
	{Sprite120: 0},
	{Sprite121: 0},
	{Sprite122: 0},
	{Sprite123: 0},
	{Sprite124: 0},
	{Sprite125: 0},
	{Sprite126: 0},
	{Sprite127: 0},
	{Sprite128: 0},
	{Sprite129: 0},
	{Sprite130: 0},
	{Sprite131: 0},
	{Sprite132: 0},
	{Sprite133: 0},
	{Sprite134: 0},
	{Sprite135: 0},
	{AssignedFrame: 0},
	{GroupID: 0},
	{IsFlipped: 0},
	{Sprite136: 0},
	{Sprite137: 0},
	{Sprite138: 0},
	{Sprite139: 0},
	{Sprite140: 0},
	{Sprite141: 0},
	{Sprite142: 0},
	{Sprite143: 0},
	{Sprite144: 0},
	{Sprite145: 0},
	{Sprite146: 0},
	{Sprite147: 0},
	{Sprite148: 0},
	{Jumpthru: 0},
	{Sine: 0},
	{Sprite149: 0},
	{Sprite150: 0},
	{ScrollTo: 0},
	{Platform: 0},
	{Sprite151: 0},
	{Sprite152: 0},
	{Sprite153: 0},
	{Sprite154: 0},
	{Sprite155: 0},
	{Sprite156: 0},
	{Sprite157: 0},
	{Sprite158: 0},
	{Sprite159: 0},
	{Sprite160: 0},
	{Sprite161: 0},
	{Sprite162: 0},
	{Sprite163: 0},
	{Sprite164: 0},
	{Sprite165: 0},
	{Touch: 0},
	{Sprite166: 0},
	{Sprite167: 0},
	{Sprite168: 0},
	{Sprite169: 0},
	{Sprite170: 0},
	{Sprite171: 0},
	{Sprite172: 0},
	{Sprite173: 0},
	{Sprite174: 0},
	{Sprite175: 0},
	{Sprite176: 0},
	{Sprite177: 0},
	{Sprite178: 0},
	{Sprite179: 0},
	{Sprite180: 0},
	{Sprite181: 0},
	{Sprite182: 0},
	{Sprite183: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Button: class extends self.IButtonInstance {},
	Button2: class extends self.IButtonInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Button3: class extends self.IButtonInstance {},
	Browser: class extends self.IInstance {},
	Sprite35: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Video: class extends self.IWorldInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	Sprite32: class extends self.ISpriteInstance {},
	Sprite33: class extends self.ISpriteInstance {},
	Sprite34: class extends self.ISpriteInstance {},
	Sprite36: class extends self.ISpriteInstance {},
	Sprite37: class extends self.ISpriteInstance {},
	Sprite38: class extends self.ISpriteInstance {},
	Sprite39: class extends self.ISpriteInstance {},
	Sprite40: class extends self.ISpriteInstance {},
	Sprite41: class extends self.ISpriteInstance {},
	Sprite42: class extends self.ISpriteInstance {},
	Sprite43: class extends self.ISpriteInstance {},
	Sprite44: class extends self.ISpriteInstance {},
	Sprite45: class extends self.ISpriteInstance {},
	Sprite46: class extends self.ISpriteInstance {},
	Sprite47: class extends self.ISpriteInstance {},
	Sprite48: class extends self.ISpriteInstance {},
	Sprite49: class extends self.ISpriteInstance {},
	Sprite50: class extends self.ISpriteInstance {},
	Sprite51: class extends self.ISpriteInstance {},
	Sprite52: class extends self.ISpriteInstance {},
	Video2: class extends self.IWorldInstance {},
	Sprite53: class extends self.ISpriteInstance {},
	Sprite54: class extends self.ISpriteInstance {},
	Sprite55: class extends self.ISpriteInstance {},
	Sprite56: class extends self.ISpriteInstance {},
	Sprite57: class extends self.ISpriteInstance {},
	Sprite58: class extends self.ISpriteInstance {},
	Sprite59: class extends self.ISpriteInstance {},
	Sprite60: class extends self.ISpriteInstance {},
	Sprite61: class extends self.ISpriteInstance {},
	Sprite62: class extends self.ISpriteInstance {},
	Sprite63: class extends self.ISpriteInstance {},
	Sprite64: class extends self.ISpriteInstance {},
	Sprite65: class extends self.ISpriteInstance {},
	Sprite66: class extends self.ISpriteInstance {},
	Sprite67: class extends self.ISpriteInstance {},
	Sprite68: class extends self.ISpriteInstance {},
	Sprite69: class extends self.ISpriteInstance {},
	Sprite70: class extends self.ISpriteInstance {},
	Sprite71: class extends self.ISpriteInstance {},
	Sprite72: class extends self.ISpriteInstance {},
	Sprite73: class extends self.ISpriteInstance {},
	Sprite74: class extends self.ISpriteInstance {},
	Sprite75: class extends self.ISpriteInstance {},
	Sprite76: class extends self.ISpriteInstance {},
	Sprite77: class extends self.ISpriteInstance {},
	Sprite78: class extends self.ISpriteInstance {},
	Sprite79: class extends self.ISpriteInstance {},
	Sprite80: class extends self.ISpriteInstance {},
	Sprite81: class extends self.ISpriteInstance {},
	Sprite82: class extends self.ISpriteInstance {},
	Sprite83: class extends self.ISpriteInstance {},
	Sprite84: class extends self.ISpriteInstance {},
	Sprite85: class extends self.ISpriteInstance {},
	Sprite86: class extends self.ISpriteInstance {},
	Sprite87: class extends self.ISpriteInstance {},
	Sprite88: class extends self.ISpriteInstance {},
	Sprite89: class extends self.ISpriteInstance {},
	Sprite90: class extends self.ISpriteInstance {},
	Sprite91: class extends self.ISpriteInstance {},
	Sprite92: class extends self.ISpriteInstance {},
	Sprite93: class extends self.ISpriteInstance {},
	Sprite94: class extends self.ISpriteInstance {},
	Sprite95: class extends self.ISpriteInstance {},
	Sprite96: class extends self.ISpriteInstance {},
	Sprite97: class extends self.ISpriteInstance {},
	Sprite98: class extends self.ISpriteInstance {},
	Sprite99: class extends self.ISpriteInstance {},
	Video3: class extends self.IWorldInstance {},
	Sprite100: class extends self.ISpriteInstance {},
	Sprite101: class extends self.ISpriteInstance {},
	Sprite102: class extends self.ISpriteInstance {},
	Sprite103: class extends self.ISpriteInstance {},
	Sprite104: class extends self.ISpriteInstance {},
	Sprite105: class extends self.ISpriteInstance {},
	Sprite106: class extends self.ISpriteInstance {},
	Sprite107: class extends self.ISpriteInstance {},
	Sprite108: class extends self.ISpriteInstance {},
	Sprite109: class extends self.ISpriteInstance {},
	Sprite110: class extends self.ISpriteInstance {},
	Sprite111: class extends self.ISpriteInstance {},
	Sprite112: class extends self.ISpriteInstance {},
	Sprite113: class extends self.ISpriteInstance {},
	Sprite114: class extends self.ISpriteInstance {},
	Sprite115: class extends self.ISpriteInstance {},
	Sprite116: class extends self.ISpriteInstance {},
	Sprite117: class extends self.ISpriteInstance {},
	Sprite118: class extends self.ISpriteInstance {},
	Sprite119: class extends self.ISpriteInstance {},
	Sprite120: class extends self.ISpriteInstance {},
	Sprite121: class extends self.ISpriteInstance {},
	Sprite122: class extends self.ISpriteInstance {},
	Sprite123: class extends self.ISpriteInstance {},
	Sprite124: class extends self.ISpriteInstance {},
	Sprite125: class extends self.ISpriteInstance {},
	Sprite126: class extends self.ISpriteInstance {},
	Sprite127: class extends self.ISpriteInstance {},
	Sprite128: class extends self.ISpriteInstance {},
	Sprite129: class extends self.ISpriteInstance {},
	Sprite130: class extends self.ISpriteInstance {},
	Sprite131: class extends self.ISpriteInstance {},
	Sprite132: class extends self.ISpriteInstance {},
	Sprite133: class extends self.ISpriteInstance {},
	Sprite134: class extends self.ISpriteInstance {},
	Sprite135: class extends self.ISpriteInstance {},
	Sprite136: class extends self.ISpriteInstance {},
	Sprite137: class extends self.ISpriteInstance {},
	Sprite138: class extends self.ISpriteInstance {},
	Sprite139: class extends self.ISpriteInstance {},
	Sprite140: class extends self.ISpriteInstance {},
	Sprite141: class extends self.ISpriteInstance {},
	Sprite142: class extends self.ISpriteInstance {},
	Sprite143: class extends self.ISpriteInstance {},
	Sprite144: class extends self.ISpriteInstance {},
	Sprite145: class extends self.ISpriteInstance {},
	Sprite146: class extends self.ISpriteInstance {},
	Sprite147: class extends self.ISpriteInstance {},
	Sprite148: class extends self.ISpriteInstance {},
	Sprite149: class extends self.ISpriteInstance {},
	Sprite150: class extends self.ISpriteInstance {},
	Sprite151: class extends self.ISpriteInstance {},
	Sprite152: class extends self.ISpriteInstance {},
	Sprite153: class extends self.ISpriteInstance {},
	Sprite154: class extends self.ISpriteInstance {},
	Sprite155: class extends self.ISpriteInstance {},
	Sprite156: class extends self.ISpriteInstance {},
	Sprite157: class extends self.ISpriteInstance {},
	Sprite158: class extends self.ISpriteInstance {},
	Sprite159: class extends self.ISpriteInstance {},
	Sprite160: class extends self.ISpriteInstance {},
	Sprite161: class extends self.ISpriteInstance {},
	Sprite162: class extends self.ISpriteInstance {},
	Sprite163: class extends self.ISpriteInstance {},
	Sprite164: class extends self.ISpriteInstance {},
	Sprite165: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Sprite166: class extends self.ISpriteInstance {},
	Sprite167: class extends self.ISpriteInstance {},
	Sprite168: class extends self.ISpriteInstance {},
	Sprite169: class extends self.ISpriteInstance {},
	Sprite170: class extends self.ISpriteInstance {},
	Sprite171: class extends self.ISpriteInstance {},
	Sprite172: class extends self.ISpriteInstance {},
	Sprite173: class extends self.ISpriteInstance {},
	Sprite174: class extends self.ISpriteInstance {},
	Sprite175: class extends self.ISpriteInstance {},
	Sprite176: class extends self.ISpriteInstance {},
	Sprite177: class extends self.ISpriteInstance {},
	Sprite178: class extends self.ISpriteInstance {},
	Sprite179: class extends self.ISpriteInstance {},
	Sprite180: class extends self.ISpriteInstance {},
	Sprite181: class extends self.ISpriteInstance {},
	Sprite182: class extends self.ISpriteInstance {},
	Sprite183: class extends self.ISpriteInstance {}
}